### ISSUE TITLE
SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by MahalakshmiG** [gusnips/node-koa-mvc#2]
While starting the server by using the below command
node --harmony app.ejs
its giving one syantax error which is shown below.

D:\koapp4\node_modules\koa-mvc\templates\app>node --harmony app.ejs
D:\koapp4\node_modules\koa-mvc\templates\app\app.ejs:13
<% if(program.css==='less'){ -%>
 ^
SyntaxError: Unexpected token %
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:842:3

**Comment by gusnips** [comment]
I don't know if you misspelled, but it should be 

> node --harmony app.js
> without the 'e'
